#We are leveraging a separate resource group for the storage account that houses the
#state files for security and safety purposes
resource_group_name  = "tfstate-rg"
storage_account_name = "tfstateaccount"
container_name       = "tfstate"
