#This file itself will be used at the ADO pipeline runtime via injection with the Terraform init cmd
#We are leveraging a separate resource group for the storage account that houses the
#state files for security and safety purposes
resource_group_name  = "terraform-rg"
storage_account_name = "terraform"
container_name       = "tfstate"
key                  = "dev.tfstate"
