trigger:
  branches:
    include:
      - main  # Adjust to your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '3.0.0'  # Set your desired version
  azureServiceConnection: 'Terraform-ADO-BuildDeploy'  # Name of your Azure service connection
  tfWorkingDirectory: './terraform'  # Path to your Terraform code

steps:
  - checkout: self

  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Installing Terraform..."
        wget https://releases.hashicorp.com/terraform/${terraformVersion}/terraform_${terraformVersion}_linux_amd64.zip
        unzip terraform_${terraformVersion}_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform -version

  - script: terraform init
    workingDirectory: $(tfWorkingDirectory)
    displayName: 'Terraform Init'

  - script: terraform plan -out=tfplan
    workingDirectory: $(tfWorkingDirectory)
    displayName: 'Terraform Plan'

  - script: terraform apply -auto-approve tfplan
    workingDirectory: $(tfWorkingDirectory)
    displayName: 'Terraform Apply'
